% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Global Data Definition File                                      
%                                                                  
% Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
%       (http://www.cs.vt.edu/~asandu/Software/KPP)                
% KPP is distributed under GPL, the general public licence         
%       (http://www.gnu.org/copyleft/gpl.html)                     
% (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
% (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
%     With important contributions from:                           
%        M. Damian, Villanova University, USA                      
%        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
%                                                                  
% File                 : mech_Global_defs.m                        
% Time                 : Fri May  7 13:51:21 2021                  
% Working directory    : /home/katie/PACT1D/new_mech_May2021/mechanism
% Equation file        : mech.kpp                                  
% Output root filename : mech                                      
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




% Declaration of global variables                                  

% C - Concentration of all species                                 
 global C;
% VAR - Concentrations of variable species (global)                
 global VAR;
% FIX - Concentrations of fixed species (global)                   
 global FIX;
% RCONST - Rate constants (global)                                 
 global RCONST;
% TIME - Current integration time                                  
 global TIME;
% SUN - Sunlight intensity between [0,1]                           
 global SUN;
% TEMP - Temperature                                               
 global TEMP;
% RTOLS - (scalar) Relative tolerance                              
 global RTOLS;
% TSTART - Integration start time                                  
 global TSTART;
% TEND - Integration end time                                      
 global TEND;
% DT - Integration step                                            
 global DT;
% ATOL - Absolute tolerance                                        
 global ATOL;
% RTOL - Relative tolerance                                        
 global RTOL;
% STEPMIN - Lower bound for integration step                       
 global STEPMIN;
% STEPMAX - Upper bound for integration step                       
 global STEPMAX;
% CFACTOR - Conversion factor for concentration units              
 global CFACTOR;

% INLINED global variable declarations                             

% INLINED global variable declarations                             

